process = [
  {
    pid: "P1",
    arrivalTime: 1,
    burstTime: 7,
    visited: false,
    waitingTime: 0,
    completionTime: 8,
    turnaroundTime: 7,
  },
  {
    pid: "P2",
    arrivalTime: 3,
    burstTime: 3,
    visited: false,
    waitingTime: 5,
    completionTime: 11,
    turnaroundTime: 8,
  },
  {
    pid: "P3",
    arrivalTime: 6,
    burstTime: 2,
    visited: false,
    waitingTime: 5,
    completionTime: 13,
    turnaroundTime: 7,
  },
  {
    pid: "P4",
    arrivalTime: 7,
    burstTime: 10,
    visited: false,
    waitingTime: 6,
    completionTime: 23,
    turnaroundTime: 16,
  },
  {
    pid: "P5",
    arrivalTime: 9,
    burstTime: 8,
    visited: false,
    waitingTime: 14,
    completionTime: 31,
    turnaroundTime: 22,
  },
];
